### ISSUE TITLE
Can't exclude files

### ISSUE THREAD

**Issue by luukvankooten** [drupal-composer/drupal-scaffold#109]
In the extra section of the composer dot json does not read it it still overwritten in the in install process.

```json
"excludes": [ "sites/development.services.yml"],
```

**Comment by leymannx** [comment]
See https://www.drupal.org/docs/develop/using-composer/using-drupals-composer-scaffold. Into the extra section put the following.

```yaml
    "extra": {
        "drupal-scaffold": {
            "file-mapping": {
                "[web-root]/sites/development.services.yml": false
            }
        }
    }
```

**Comment by greg-1-anderson** [comment]
The comment above shows the instructions on using the project `drupal/core-composer-scaffold`, which is now preferred to this project.
