### ISSUE TITLE
Make sure the the plugin works on Windows

### ISSUE THREAD

**Issue by webflo** [drupal-composer/drupal-scaffold#11]

**Comment by divined** [comment]
[FileSystem\FilesystemStack] mkdir ["C:\\OpenServer\\cygwin64\\tmp\\drupal-scaffold-1464024156"]
 [FileSystem\FilesystemStack] mkdir ["C:\\Users\\Val_S\\drupal\\web\/sites\/default"]
 [FileSystem\FilesystemStack] _chmod ["C:\\Users\\Val_S\\drupal\\web\/sites\/default",493]
 [FileSystem\CleanDir] Cleaned C:\OpenServer\cygwin64\tmp\drupal-scaffold-1464024156
>  Attempt to download https://ftp.drupal.org/files/projects/drupal-8.1.1.tar.gz to C:\OpenServer\cygwin64\tmp\drupal-scaffold-1464024156/drupal-8.1.1.tar.gz
 [Archive\Extract] Extracting C:\OpenServer\cygwin64\tmp\drupal-scaffold-1464024156/drupal-8.1.1.tar.gz
 [Archive\Extract] C:\OpenServer\cygwin64\tmp\drupal-scaffold-1464024156/drupal-8.1.1.tar.gz extracted
 [FileSystem\FilesystemStack] _rename ["C:\\Users\\Val_S\\drupal\/tmp206831464024160\/drupal-8.1.1","C:\\OpenServer\\cygwin64\\tmp\\drupal-scaffold-1464024156\/drupal-8"]
 [FileSystem\DeleteDir] Deleted C:\Users\Val_S\drupal/tmp206831464024160...
 [Remote\Rsync] Running rsync -a -v -z --no-group --no-owner --include "sites" --include "sites/default" --include "sites/default/default.settings.php" --include "sites/default/default.services.yml" --include "sites/development.services.yml" --include "sites/example.settings.local.php" --include "sites/example.sites.php" --exclude ".gitkeep" --exclude "autoload.php" --exclude "composer.json" --exclude "composer.lock" --exclude "core" --exclude "drush" --exclude "example.gitignore" --exclude "LICENSE.txt" --exclude "README.txt" --exclude "vendor" --exclude "themes" --exclude "profiles" --exclude "modules" --exclude "sites/*" --exclude "sites/default/*" "C:\OpenServer\cygwin64\tmp\drupal-scaffold-1464024156/drupal-8/" "C:\Users\Val_S\drupal\web"
**The source and destination cannot both be remote.**
rsync error: syntax or usage error (code 1) at main.c(1292) [Receiver=3.1.2]

**Comment by greg-1-anderson** [comment]
GitHub should have divined from my "(maybe)" that this issue should not have been closed yet. :)

There are still rsync problems here.  The robo CopyDir task now takes an "exclude" parameter; perhaps we can use this facility to replace rsync with CopyDir in drupal-scaffold.

**Comment by webflo** [comment]
Merged #38 a few minutes ago.
