### ISSUE TITLE
Problems with pear/archive_tar package

### ISSUE THREAD

**Issue by hctom** [drupal-composer/drupal-scaffold#15]
@greg-1-anderson: I just found some problems with the new ```pear/archive_tar``` package used for untaring the scaffold files. 
Unfortunately this seems to require an existing PEAR installation in your PHP include path, because in ```pear/archive:tar/Archive/Tar.php``` there is the following statement:

```require_once 'PEAR.php';```

Of course the PEAR minimal core is added via Composer, but this does not solve the hard-coded ```require```.

In my case, I cannot work with ```drupal-composer/drupal-scaffold```because it always breaks with the following error:

![](http://share.undpaul.de/bilder/tk/297wd-2015-12-11-11-25-53.png)

Perhaps it is better to use the following package for untaring the scaffold files:

https://packagist.org/packages/alchemy/zippy

I'm looking forward to your feedback & thanx in advance!

**Comment by greg-1-anderson** [comment]
That does appear to be a problem.  I will re-implement the PR using the package that you suggest. Zippy is used by Drupal/Console, so it seems likely that it has enough exposure to be generally usable.

As an aside, I am wondering if @htcom has used [drush-ops/drush](https://github.com/drush-ops/drush) version 7 or 8, which use the Pear Console table, which it installs via Composer. I am wondering if it has the same problem.

**Comment by hctom** [comment]
Yes, I have Drush installed in 7 and 8... but I checked the Console table package and that file does not contain the ```require``` statement. I guess that did the trick there ;)

So I am really looking forward to the reworked untaring, as this is really a cool must-have to set up Drupal via Composer.
