### ISSUE TITLE
autoloader.php

### ISSUE THREAD

**Issue by hctom** [drupal-composer/drupal-scaffold#16]
Currently you have to create the ```autoloader.php``` manually to get a Drupal project up and running in combination with ```drupal-composer/drupal-scaffold```.

My suggestion is to implement a check, if there is an ```autoloader.php``` file available in the document root of Drupal. If not, ```drupal-composer/drupal-scaffold``` should create a default autoloader file pointing to the correct vendor directory (in most cases outside of the document root).

May this work out, or should users always create it manually (if so, this might be worth a short note in the ```README.md```, hehe)?

**Comment by greg-1-anderson** [comment]
At the moment, drupal-scaffold is designed to be used in conjunction with a template project such as [drupal-composer/drupal-project](https://github.com/drupal-composer/drupal-project) that already contains the necessary structure, including the autoload.php file, needed to use Drupal.

However, it would be completely possible for drupal-scaffold to generate the autoload file if it does not exist. This is a good idea.

**Comment by hctom** [comment]
@greg-1-anderson: I finally got the time to install your new features. From now on I get the following error:

```Fatal error:  Class 'DrupalComposer\DrupalScaffold\Filesystem' not found in vendor/drupal-composer/drupal-scaffold/src/Handler.php on line 204```

I guess there is a namespace missing, isn't it?

**Comment by greg-1-anderson** [comment]
Sorry, I was in a hurry on Friday and tested the wrong branch after I merged. Fixed in latest HEAD of master, but only lightly tested. It does update scaffold files and write the autoload.php file.
