### ISSUE TITLE
Tag version 1.0.0.

### ISSUE THREAD

**Issue by greg-1-anderson** [drupal-composer/drupal-scaffold#22]
We're about to use drupal-scaffold in drupal-project.  Let's tag a 1.0.0 release, so that folks have a stable tag referring specifically to the behavior embodied in this version. That way, if we need to go to 2.x for a breaking change, ~1 will still be available.

**Comment by derhasi** [comment]
:+1:

**Comment by webflo** [comment]
Lets add the branch alias first. (#23)

**Comment by greg-1-anderson** [comment]
Tagged and pushed; Packagist auto-updated with the new version.
