### ISSUE TITLE
Support Drupal Core 7.x and lower

### ISSUE THREAD

**Issue by lpalgarvio** [drupal-composer/drupal-scaffold#31]
Hello

Can we get Drupal Core 7.x and lower supported?
What are the challenges for that?

This patch I'm providing allows filtering the release version (7.x vs 8.x.x) properly and feeding it to the RoboRunner in downloadScaffold() in Handler.php
[fix-d7.patch.txt](https://github.com/drupal-composer/drupal-scaffold/files/199500/fix-d7.patch.txt)

However, Drupal 7.x packages do not exist in the drupal/core namespace (while Drupal 8.x packages exist in both, but not the latest?)

I made this other patch to change the drupal/core to drupal/drupal in the code to allow Drupal 7:
[drupal-core-drupal.patch.txt](https://github.com/drupal-composer/drupal-scaffold/files/199499/drupal-core-drupal.patch.txt)

Then you just have to override the includes/excludes to have it download drupal7 and scaffold it.

But I'm aware this last patch is not the best way. It will need a version selector, just like the first patch. Maybe we can have a function for this.

Let me know what you think before proceeding with more changes.
Cheers

**Comment by derhasi** [comment]
drupal-scaffold does not make sense for D7 and below, as you will always have to work with the `drupal/drupal` package in a composer based workflow. Therefore you already have all your scaffold files present.

In addition you might use https://github.com/derhasi/composer-preserve-paths to allow some files to be overriden. See https://github.com/drupal-composer/drupal-project/tree/7.x for an example.
