### ISSUE TITLE
Copying from temporary directory is slow

### ISSUE THREAD

**Issue by bartfeenstra** [drupal-composer/drupal-scaffold#35]
`[FileSystem\CopyDir] Copied from /build_dir/tmp3803384641461926325/drupal-8.0.6 to /tmp/drupal-scaffold-1461926324/drupal-8`

This step in the scaffolding process seems to take the most time, presumably because it copies all of core's files *after* they have been extracted. Would it be possible to perform the tarball extraction after this copy, so the copy action becomes faster?

I may have time to work on this myself later. If not, this issue serves as a reminder.

**Comment by webflo** [comment]
I think its possible to skip the copy step command and rsync from the temp dir directly

**Comment by webflo** [comment]
Merged #38 a few minutes ago. I think its faster the previous implementation.

**Comment by bartfeenstra** [comment]
Thanks a lot! Sorry I haven't been able to work on this myself. Crazy project schedule :X
