### ISSUE TITLE
Allow scaffolding with custom upstreams

### ISSUE THREAD

**Issue by derekderaps** [drupal-composer/drupal-scaffold#36]
Would be great to scaffold with a forked upstream of the "subtree split" repo, such as Pantheon's [drupal-core](https://github.com/pantheon-systems/drupal-core), which uses their forked Drupal 8 core, [drops-8](https://github.com/pantheon-systems/drops-8).

**Comment by RobLoach** [comment]
Since we're building Drupal rather then checking it out from a git repository, the upstream workflow on Pantheon gets a bit iffy. One way to have this push to Pantheon would be:

1. Instead of using `drupal/core` in composer.json, you'd use Greg's `pantheon-systems/drupal-core`
2. Use something like [Robo's VCS Tasks](http://robo.li/tasks/Vcs/) to force push the `docroot` folder to Pantheon

**Comment by andrewmallis** [comment]
As Rob notes we can create a custom upstream that is a production build managed by our CI. Here's how: https://pantheon.io/docs/custom-upstream/
updates will come in to the dashboard and need to be applied.

We can also create a site with no upstream at all:
https://kalamuna.atlassian.net/wiki/display/KALA/Creating+a+Pantheon+website+with+no+defined+upstream
which simply cleans up the dashboard prompts to update an irrelevant distro.

**Comment by derekderaps** [comment]
I should have mentioned what aI already tried. E.g., @RobLoach's suggestion
>1. Instead of using drupal/core in composer.json, you'd use Greg's pantheon-systems/drupal-core
Doesn't work. There is additional scaffolding code that expects to see the `drupal/core` repo. Changing that code to `pantheon-systems/drupal-core` got it further along but then error'd out on something else I don't remember.

@andrewmallis re:
>As Rob notes we can create a custom upstream that is a production build managed by our CI. Here's how: https://pantheon.io/docs/custom-upstream/
updates will come in to the dashboard and need to be applied.
We don't use Pantheon to apply updates since we develop our code in a separate repo. Perhaps Pantheon's rumored 3rd party repo integration will help.

And anyway in this case, the only "custom upstream" that works is [vanilla drupal core](https://github.com/drupal/drupal), which of course doesn't have the usual modifications that Pantheon makes to core. We can use composer to apply patches, but I don't want to get into the business of keeping up with Pantheon's core modifications. They seem to be relatively minor in Drupal 8 as compared to Drupal 7, so maybe this won't be too bad.

**Comment by RobLoach** [comment]
> Doesn't work. 

Likely because the subtree split needs an update: https://github.com/drupal-composer/drupal-core/issues/11 . https://packagist.org/packages/pantheon-systems/drupal-core is at beta12.

**Comment by derekderaps** [comment]
> Likely because the subtree split needs an update: drupal-composer/drupal-core#11 . https://packagist.org/packages/pantheon-systems/drupal-core is at beta12.

Nerp. The repo doesn't actually contain the code for drupal core, just a reference to the drupal core repo. The [official split repo](https://github.com/drupal-composer/drupal-core) hasn't been updated since August 11th, 2015. And the only commit since Pantheon forked is a few lines of documentation. [Pantheon's split core](https://github.com/pantheon-systems/drupal-core) is two commits ahead, and the only changes are simply to reference [drops-8](https://github.com/pantheon-systems/drops-8).

**Comment by webflo** [comment]
#38 Should work with custom upstreams as well. Just defined a different source url and additional includes.
