### ISSUE TITLE
Package codegyre/robo is abandoned

### ISSUE THREAD

**Issue by landsman** [drupal-composer/drupal-scaffold#53]
Hello,
I was found this message after composer update:
`Package codegyre/robo is abandoned, you should avoid using it. Use consolidation/robo instead.`

On this package is message: `This package is abandoned and no longer maintained. The author suggests using the consolidation/robo package instead.` - see: https://packagist.org/packages/codegyre/robo

Can you replace this lib please?

**Comment by derhasi** [comment]
The package has been removed in `2.x`.
Simply to the newest release and you should not run in that message anymore: e.g. via `composer require drupal-composer/drupal-scaffold:"2.*"`
