### ISSUE TITLE
Composer TransportException, empty 200 response

### ISSUE THREAD

**Issue by weseze** [drupal-composer/drupal-scaffold#59]
I have been using the scaffolding project for a few months now for a few drupal sites and I have never been able to correctly get all the scaffolding files.
Any composer install/update command always fails, and I always have to manually get the correct scaffolding files.

This is the error I receive:
Installation failed, reverting ./composer.json to its original content.

  [Composer\Downloader\TransportException]
  "http://cgit.drupalcode.org/drupal/plain/.csslintrc?h=8.2.6" appears broken, and returned an empty 200 response

It is not related to a single file, sometimes it downloads 1 file, sometimes, 2, 3, 4, 5, ... But it always fails somewhere.

What might cause this issue?
Is there a way to tell compose to try again when it fails? Because I have a feeling it would all work if composer would just try again to download the file.

**Comment by igasi** [comment]
This error appears me frequently when I updated and I need to rebuild my instance. At the first, I was thinking that was due to my network, but the error appears at the same time in 2 different locations and networks after many attempts work again.

**Comment by webflo** [comment]
@igasi Have you used the newest release of drupal-scaffold?

**Comment by webflo** [comment]
@igasi You could try to change the scaffold url to github, maybe thats more reliable

**Comment by igasi** [comment]
@webflo I updated the version, I was using the 2.2.0, I had the URL of the github too.
I ran well now. But the error is weird sometimes appears and sometimes no. If the problem continues I'll comment again.

Thanks!!

**Comment by webflo** [comment]
No one has reported this bug since then. Please re-open if its still an issue.
