### ISSUE TITLE
Drupal-l10n

### ISSUE THREAD

**Issue by FlorentTorregrosa** [drupal-composer/drupal-scaffold#64]
Hello,

I just made a new composer plugin to download Drupal localization files using composer. The structure comes from drupal-scaffold.

Here is the repository: https://github.com/FlorentTorregrosa/drupal-l10n

Here is an usage example: https://github.com/FlorentTorregrosa/docker-drupal-project/commit/183a92c73a606a44e5aebcc361385ad9e6b2d4d1

Why this plugin? (https://github.com/FlorentTorregrosa/drupal-l10n/blob/master/README.md#usage)

This plugin is useful when you want to package your project and then deploy this package on a target environment and that this environment does not have access to a localization servers. So you have to prepare the translations before deploying.

It avoids you to have to put the localization files under your VCS or to have a local site to download the translations.

So does the drupal-composer group would like to incorporate it or should it stay on my Github account?

In TODO I have to:
- [x] Implement proper Composer events, currently only the download method works.
- [x] Implement tests
- [x] Display the name of the file that is downloaded (I have the same problem with drupal-scaffold, the filename is not displayed)

Thanks for your reply.

**Comment by greg-1-anderson** [comment]
This looks like a very useful plugin. I think it would be great to have it in the drupal-composer org, but that's up to @webflo and @derhasi.

**Comment by FlorentTorregrosa** [comment]
Hello,

@webflo, @derhasi would it be possible to have a feedback please?

**Comment by derhasi** [comment]
It looks like an interesting plugin, but could not test it yet.

**Comment by FlorentTorregrosa** [comment]
Hello,

Any news on this issue?

**Comment by FlorentTorregrosa** [comment]
Hello,

I talked about that with @webflo at the Drupal dev Days Lisbon.

Suggestions:
* provide command under drupal namespace like other drupal-composer composer extension: `composer drupal:l10n`
* use drupal_rewrite_settings to update settings.php according to the configuration in composer.json file.

**Comment by FlorentTorregrosa** [comment]
Thanks @webflo for creating https://github.com/drupal-composer/drupal-l10n.

I am closing this issue. I have opened followup issues in the new Github repository.
