### ISSUE TITLE
Fatal error: Interface 'Composer\Plugin\Capability\CommandProvider' not found

### ISSUE THREAD

**Issue by DieterHolvoet** [drupal-composer/drupal-scaffold#86]
I'm getting an error during `composer install` of `drupal-composer/drupal-scaffold` on version 2.5.2:
```
Fatal error: Interface 'Composer\Plugin\Capability\CommandProvider' not found in <redacted>/vendor/drupal-composer/drupal-scaffold/src/CommandProvider.php on line 10
```

**Comment by greg-1-anderson** [comment]
What version of Composer are you running? Try `composer selfupdate` and see if it starts working.

**Comment by DieterHolvoet** [comment]
```
Composer version @package_branch_alias_version@ (1.0.0-beta2) 2016-03-27 16:00:34
```
Obviously we should update, but isn't it possible for you to indicate the required version of composer needed for the package to function?

**Comment by greg-1-anderson** [comment]
I thought there was a check for the Composer version in there somewhere. Perhaps for sufficiently ancient versions of Composer, the failure happens before the check. I didn't attempt to reproduce though.

**Comment by webflo** [comment]
1.0.0-beta2 is a an ancient version. You you try to install the last composer release? Thanks!
